### ISSUE TITLE
Is there a way to extract the background & letter?

### ISSUE THREAD

**Issue by quiin** [IvBaranov/MaterialLetterIcon#10]
I would like to use the background and letter so I can use it in an Image View. Is it currently posible?

**Comment by IvBaranov** [comment]
You can set background image in xml like this:
```
    <com.github.ivbaranov.mli.MaterialLetterIcon
        android:id="@+id/icon"
        android:layout_width="@dimen/list_item_avatar_size"
        android:layout_height="@dimen/list_item_avatar_size"
        android:background="@drawable/meme" />
```

and use transparent color for shape:
```
materialLetterIcon.setShapeColor(Color.TRANSPARENT);
```

So you can get something like this:

<img src="https://cloud.githubusercontent.com/assets/6000572/22327316/9e4a4354-e3c7-11e6-8d1a-2c34456510bb.png" width="250" />

However this is hack rather than feature of MaterialLetterIcon right now.
